best: True
resume: False
seed: 1234
cuda: True
m: 1
n_saved_samples: 0
data_name: intel
data_dir: /s/chopin/l/grad/stock/nvme/data/cs/intel-img/
ckpt_dir: ../ckpt/hyper/intel
plot_dir: None
standardize_x: False
n_outputs: 6
c: 3
use_memory: False
shuffle: True
normalize_loss: False
model_name: ram_003
g: 16
k: 3
s: 2
h_g: 1024
h_l: 64
n_hiddens: 1024
loc_std: 0.1
n_heads: 0
dim_feedforward: 0
dropout: 0
epochs: 400
n_glimpses: 8
lr: 0.0003
lr_patience: 20
batch_size: 128
train_patience: 60
