best: True
resume: False
seed: 1234
cuda: True
m: 1
n_saved_samples: 0
data_name: cluttered
data_dir: /s/chopin/l/grad/stock/nvme/data/cs/cluttered-mnist
ckpt_dir: ../ckpt/hyper/cluttered
plot_dir: None
standardize_x: False
n_outputs: 10
c: 1
use_memory: True
shuffle: True
normalize_loss: False
model_name: ours_006
g: 12
k: 3
s: 2
h_g: 512
h_l: 64
n_hiddens: 256
loc_std: 0.1
n_heads: 1
dim_feedforward: 256
dropout: 0.1
epochs: 400
n_glimpses: 6
lr: 0.0003
lr_patience: 20
batch_size: 128
train_patience: 40
