model_name: e03

# network params
g: 32
k: 2
s: 2
h_g: 128
h_l: 128
n_hiddens: 256
loc_std: 0.05

# memory params
h_m: 64
use_memory: False

# training params
epochs: 100
n_glimpses: 6
lr: 0.0003
lr_patience: 20
batch_size: 32
shuffle: True
train_patience: 40

# testing params
m: 5
n_saved_samples: 3

# data params
data_name: tc
data_dir: /s/chopin/l/grad/stock/nvme/data/ai2es/mlhub/nasa_tc
ckpt_dir: ../ckpt
plot_dir: ../plots
standardize_x: True
n_outputs: 3
c: 1

# misc params
best: True
resume: False
seed: 1234
cuda: True