best: True
resume: False
seed: 1234
cuda: True
m: 1
n_saved_samples: 0
data_name: mnist
data_dir: /s/chopin/l/grad/stock/nvme/data/cs/
ckpt_dir: ../ckpt/hyper/mnist
plot_dir: None
standardize_x: False
n_outputs: 10
c: 1
use_memory: False
shuffle: True
normalize_loss: False
model_name: ram_033
g: 8
k: 1
s: 1
h_g: 256
h_l: 64
n_hiddens: 256
loc_std: 0.05
n_heads: 0
dim_feedforward: 0
dropout: 0
epochs: 300
n_glimpses: 6
lr: 0.0003
lr_patience: 20
batch_size: 128
train_patience: 40
