best: True
resume: False
seed: 1234
cuda: True
m: 1
n_saved_samples: 2
data_name: tc
data_dir: /s/chopin/l/grad/stock/nvme/data/ai2es/mlhub/nasa_tc
ckpt_dir: ../ckpt/hyper/tc
plot_dir: ../plots/best/tc2
standardize_x: False
n_outputs: 2
c: 1
use_memory: True
shuffle: True
normalize_loss: False
model_name: ours_000
g: 16
k: 3
s: 2
h_g: 256
h_l: 64
n_hiddens: 256
loc_std: 0.1
n_heads: 2
dim_feedforward: 128
dropout: 0.1
epochs: 400
n_glimpses: 12
lr: 0.0003
lr_patience: 20
batch_size: 64
train_patience: 40
